### ISSUE TITLE
hyperlink of "Penn Treebank Parsed" is broken

### ISSUE THREAD

**Issue by hitvoice** [yikangshen/Ordered-Neurons#1]
The hyperlink of "Penn Treebank Parsed" in ReadMe.md is broken and I can not find the correct download link. Is [this](https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/corpora/dependency_treebank.zip) the same? I found this link on the page [NLTK data](http://www.nltk.org/nltk_data/).

**Comment by shawntan** [comment]
Thanks for letting us know. The right link is: https://catalog.ldc.upenn.edu/LDC99T42

**Comment by hitvoice** [comment]
Thanks a lot!
