### ISSUE TITLE
How to train parsing

### ISSUE THREAD

**Issue by ronsoohyeong** [yikangshen/Ordered-Neurons#11]
Hi
I wonder how to train parsing. The main.py seems to be only for training LM.

Besides, when I try testing the parsing, `python test_phrase_grammar.py --cuda` gives error of `No such file or directory: 'PTB.pt'`. 

Best regards,
Ron

**Comment by ronsoohyeong** [comment]
Sorry. Let me first train LM and test the unsupervised parsing.

**Comment by shawntan** [comment]
The model used to perform parsing is the language model. There is no additional training performed beyond the language modelling objective.
