### ISSUE TITLE
What does the chunk_size mean in the ONLSTMStack object?

### ISSUE THREAD

**Issue by alvations** [yikangshen/Ordered-Neurons#12]
From the argparser, there is this variable `chunk_size`, it’s described as “number of units per chunk”. What does this chunk refer to? Is it a mini-batch? Or part of a batch? Or part of the sequence length? 

Is it related to the paragraph before section 5 in the paper?

> As the master gates only focus on coarse-grained control, modeling them with the same dimensions as the hidden states is computationally expensive and unnecessary. In practice, we set ˜ft and ˜it to be Dm = D C dimensional vectors, where D is the dimension of hidden state, and C is a chunk size factor. We repeat each dimension C times, before the element-wise multiplication with ft and it. The downsizing significantly reduces the number of extra parameters that we need to add to the LSTM. Therefore, every neuron within each C-sized chunk shares the same master gates.

 where the hidden state of the RNN cell is split into chunk and computed individually? If so, could you give an example of what the chunk and hidden state computation looks like?

**Comment by yikangshen** [comment]
A chunk is a group of neurons inside the cell state. The `chunk_size` means the number of neurons in each group. Each chunk is controlled by one unit in the master gates.
