### ISSUE TITLE
question about on-lstm hidden states initialization ?

### ISSUE THREAD

**Issue by robbine** [yikangshen/Ordered-Neurons#13]
I find that hidden vector is initialized only at the beginning with zero value.
Then for each batch, hidden vector is detached by calling
> hidden = repackage_hidden(hidden)

My question is why not create a new hidden vector for each batch instead of using the old ones.
> hidden = model.init_hidden(batch_size)

**Comment by yikangshen** [comment]
This part of the code is inherited from [the pytorch language model example](https://github.com/pytorch/examples/tree/master/word_language_model).
The basic idea is that the entire corpus is treated as one single long sequence. So the model needs to pass the last hidden state to the next batch. In other words,  during training, we don't reinitialize the hidden state at the beginning of each sentence.
