### ISSUE TITLE
Confusion on eq. 15

### ISSUE THREAD

**Issue by amy-deng** [yikangshen/Ordered-Neurons#2]
Dear Yikang,

I am new to NLP but I really like this paper and appreciate your work. Now I am reading the paper and have a question about Eq. 15 in section 5.2. What does y_t mean?  Thank you!

**Comment by yikangshen** [comment]
Please check the newest version of our paper (https://openreview.net/pdf?id=B1l6qiR5F7). The y_t is actually d_t. 
Sorry for being misleading.

**Comment by amy-deng** [comment]
Thanks!
