### ISSUE TITLE
two evaluation result in test_phrase_grammar.py, which is reported in the paper? 

### ISSUE THREAD

**Issue by ZhiYuanZeng** [yikangshen/Ordered-Neurons#23]
It seems that there are two evaluation result in test_phrase_grammar.py(one comes from evalb software, the other is computed by yourself), which is reported in the paper? what is the difference between them?

**Comment by yikangshen** [comment]
The evalb results are reported in our paper. My evaluation code is only for the prepose to better understand the structure and debugging.
