### ISSUE TITLE
Where is `corpus` object

### ISSUE THREAD

**Issue by yuhui-zh15** [yikangshen/Ordered-Neurons#3]
Hi, I found `test_phrase_grammar.py` referring `corpus` object many times, but I didn't find the definition and initialization.

**Comment by yikangshen** [comment]
https://github.com/yikangshen/Ordered-Neurons/blob/6fd9ebd9f7c49bb57eb2eff19fa4033b5460e1a9/test_phrase_grammar.py#L281
