### ISSUE TITLE
High performance for right-branching strategy

### ISSUE THREAD

**Issue by marcwww** [yikangshen/Ordered-Neurons#4]
Really appreciate for releasing the code.

I found when I testing the baseline of **right-branching** strategy on **WSJ test set**, the F1 is really high (**39.87**), which does not match the result in the paper (**16.5**). 

I have just changed the [code](https://github.com/yikangshen/Ordered-Neurons/blob/master/test_phrase_grammar.py#L152)
```python
distance = model.distance[0].squeeze().data.cpu().numpy()
distance_in = model.distance[1].squeeze().data.cpu().numpy()
```
into 
```python
distance = numpy.array([numpy.arange(len(sen), 0, -1)] * 3)
distance_in = numpy.array([numpy.arange(len(sen), 0, -1)] * 3)
```
, which represent a right-branching strategy.

And the result on WSJ test set is:
![image](https://user-images.githubusercontent.com/10141302/54025722-59635680-41d6-11e9-972b-f93f0b242d81.png)

So, what my be the reason? Thanks a lot if u could help me out.

**Comment by yikangshen** [comment]
We was using the baseline from previous paper. Please check the newest version of our paper for our own baseline score. https://openreview.net/pdf?id=B1l6qiR5F7

**Comment by marcwww** [comment]
That is really helpful. Thanks for your reply. 👍 

b.t.w., the previous paper did the evaluation without preprocessing to filter out the punctuations. That matters a lot for the evaluation result, which might be because the punctuations usually appear in the high-level compositions.
