### ISSUE TITLE
Processing of variable length sequences in a batch

### ISSUE THREAD

**Issue by GYM13** [yikangshen/Ordered-Neurons#5]
Hello, I just started learning the language model.I am very interested in your method after reading your paper.But after I read the paper carefully, I have a question and I would like to ask you.But after I read the paper carefully, I have a question and I would like to ask you for advice.In the paper, you directly divide the words in the corpus into equal-length batches.But now every sentence in a batch is different in length, how should I handle it?I queried the handling of the official pytorch documentation（nn.utils.rnn.pad_packed_sequence）.But don't know if this method is right for your code.Can you please give me some advice?
                                                                                                                                    Thanks

**Comment by shawntan** [comment]
`nn.utils.rnn.pad_packed_sequence` this method wouldn't work with the way this model is implemented.

Depending on what your needs are, you might have to either:
1. Mask the irrelevant hidden states (if you are doing something like an attention mechanism), or,
2. Extract the final hiddenstate of the sequence, you can look at our logical inference code for how we did that.
