### ISSUE TITLE
question about visualization

### ISSUE THREAD

**Issue by bojone** [yikangshen/Ordered-Neurons#8]
Hello, I am interested in ON-LSTM and I want to reimplement it under Keras.

I trained a Chinese language model with ON-LSTM and then export the distance (as you do in https://github.com/yikangshen/Ordered-Neurons/blob/master/ON_LSTM.py#L89 ). However, I found all elements of distance is quite close to 1 (0.995, 0.99, 0.98, ...). 

Is it a normal phenomenon in your experience ?

**Comment by yikangshen** [comment]
I didn't observe similar situation for English language model. But maybe you need to tune the hyper-parameters.

**Comment by soloist97** [comment]
@bojone Hi, I tried ON-LSTM in an image captioning model and I also observed a similar phenomenon (distance close to 1 or 0). Did you figure how to tune the hyper-parameters?
