### ISSUE TITLE
question about unidirectional

### ISSUE THREAD

**Issue by bojone** [yikangshen/Ordered-Neurons#9]
In your paper, you use a unidirectional ON-LSTM to trained a language model and then phrase grammar with the output distance of the pretrained language model. How can we explain that the level of first token is independent with the future tokens? Is there any bidirectional way to do it?

**Comment by yikangshen** [comment]
I think you can try bidirection language model (e.g. elmo) or masked language model (e.g. bert). But the perplexity won't be comparable to previous language models.

**Comment by bojone** [comment]
I am confused of how can we calculate distance if we use bi-on-lstm?  the average of distances of forward and backward on-lstm ?

**Comment by speedcell4** [comment]
@bojone I get confused on the same question, did you figure it out?
